local UILibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/0xziess/ikiykiyu/refs/heads/main/test.lua"))()

local Window = UILibrary:CreateWindow("infinity.")

-- Create tabs
local CombatTab = Window:AddTab("Farming")
local VisualsTab = Window:AddTab("Rifts")
local MiscTab = Window:AddTab("Settings")

-- Combat Tab Sections
local AimbotSection = CombatTab:AddSection("Auto")
AimbotSection:AddToggle("Auto Blow", false, function(value)
    print("Blow:", value)
end)
AimbotSection:AddToggle("Auto Sell (broken)", false, function(value)
    print("Sell:", value)
end)
AimbotSection:AddSlider("Aimbot FOV", 30, 500, 120, function(value)
    print("Aimbot FOV:", value)
end)
AimbotSection:AddDropdown("Aimbot Target", {"Head", "Torso", "Random"}, "Head", function(selected)
    print("Aimbot Target:", selected)
end)

local TriggerSection = CombatTab:AddSection("Enchanting")
TriggerSection:AddToggle("Enable Trigger Bot", false, function(value)
    print("Trigger Bot:", value)
end)
TriggerSection:AddSlider("Trigger Delay", 0, 1000, 100, function(value)
    print("Trigger Delay:", value)
end)

-- Visuals Tab Sections
local ESPSection = VisualsTab:AddSection("ESP")
ESPSection:AddToggle("Player ESP", false, function(value)
    print("Player ESP:", value)
end)
ESPSection:AddToggle("Box ESP", false, function(value)
    print("Box ESP:", value)
end)
ESPSection:AddToggle("Skeleton ESP", false, function(value)
    print("Skeleton ESP:", value)
end)
ESPSection:AddToggle("Name ESP", false, function(value)
    print("Name ESP:", value)
end)
ESPSection:AddToggle("Health ESP", false, function(value)
    print("Health ESP:", value)
end)

local ChamsSection = VisualsTab:AddSection("Chams")
ChamsSection:AddToggle("Player Chams", false, function(value)
    print("Player Chams:", value)
end)
ChamsSection:AddDropdown("Chams Material", {"ForceField", "Neon", "Plastic"}, "ForceField", function(selected)
    print("Chams Material:", selected)
end)

-- Misc Tab Sections
local ServerSection = MiscTab:AddSection("Server")
ServerSection:AddButton("Rejoin Server", function()
    print("Rejoining server...")
end)
ServerSection:AddButton("Server Hop", function()
    print("Server hopping...")
end)

local SettingsSection = MiscTab:AddSection("Settings")
SettingsSection:AddTextbox("Custom Name", "", "Enter name...", function(text)
    print("Custom Name:", text)
end)
SettingsSection:AddToggle("Auto-Execute", false, function(value)
    print("Auto-Execute:", value)
end)
